package org.openstreetmap.josm.plugins.wayheatmaptracer.util;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.awt.image.BufferedImage;
import java.util.List;
import java.util.OptionalDouble;
import java.util.Set;
import java.util.concurrent.atomic.AtomicReference;
import java.util.concurrent.atomic.AtomicLong;

import javax.swing.SwingUtilities;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openstreetmap.josm.command.AddCommand;
import org.openstreetmap.josm.data.UndoRedoHandler;
import org.openstreetmap.josm.data.coor.LatLon;
import org.openstreetmap.josm.data.osm.DataSet;
import org.openstreetmap.josm.data.osm.Node;
import org.openstreetmap.josm.data.osm.Relation;
import org.openstreetmap.josm.data.osm.RelationMember;
import org.openstreetmap.josm.data.osm.Way;
import org.openstreetmap.josm.data.projection.ProjectionRegistry;
import org.openstreetmap.josm.data.projection.Projections;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.AlignmentConfig;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.AlignmentEditPlan;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.AlignmentMode;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.GeometryCleanupConfig;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.GeometryCleanupMode;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.FinalRoutePointId.ExistingWayNodeOccurrence;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.InferenceMode;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.IntensitySamplingMode;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.JunctionPolicy;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.ManagedHeatmapConfig;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.RecoveryPermissions;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.PrimitiveKey;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.SelectionContext;
import org.openstreetmap.josm.plugins.wayheatmaptracer.model.TrackerMode;
import org.openstreetmap.josm.plugins.wayheatmaptracer.service.LiveBPreviewService;
import org.openstreetmap.josm.plugins.wayheatmaptracer.service.ManagedModernPreviewSource;
import org.openstreetmap.josm.plugins.wayheatmaptracer.service.evidence.SupportedInputRasterTransform;
import org.openstreetmap.josm.plugins.wayheatmaptracer.service.snapshot.LiveNetworkSnapshotValidator;
import org.openstreetmap.josm.plugins.wayheatmaptracer.service.snapshot.NetworkSnapshotCapture;
import org.openstreetmap.josm.plugins.wayheatmaptracer.service.tracing.CancellationProbe;
import org.openstreetmap.josm.plugins.wayheatmaptracer.service.tracing.ModernSingleWayEditPlanAdapter;
import org.openstreetmap.josm.spi.preferences.Config;
import org.openstreetmap.josm.spi.preferences.MemoryPreferences;

/** Host transaction checks using a plan generated by the real captured interior-junction path. */
class V022ProductionNetworkTransactionTest {
    @BeforeAll
    static void configureJosm() {
        Config.setPreferencesInstance(new MemoryPreferences());
        ProjectionRegistry.setProjection(Projections.getProjectionByCode("EPSG:3857"));
    }

    @BeforeEach
    void clearHostHistory() {
        UndoRedoHandler.getInstance().clean();
    }

    @AfterEach
    void leaveHostHistoryClean() {
        UndoRedoHandler.getInstance().clean();
    }

    @Test
    void everyMutationPhaseRollsBackRealInteriorJunctionPlan() throws Exception {
        Fixture fixture = fixture();
        V022AtomicApplyTest.LiveState before =
                V022AtomicApplyTest.LiveState.capture(fixture.dataSet());
        for (ApplyAlignmentEditPlanCommand.MutationPoint point
                : ApplyAlignmentEditPlanCommand.MutationPoint.values()) {
            ApplyAlignmentEditPlanCommand command = new ApplyAlignmentEditPlanCommand(
                    fixture.dataSet(), fixture.plan(), fixture.validator(),
                    "Inject real network failure", reached -> {
                        if (reached == point) {
                            throw new InjectedFailure(point);
                        }
                    });
            IllegalStateException failure = assertThrows(IllegalStateException.class,
                    () -> V022AtomicApplyTest.onEdt(() ->
                            UndoRedoHandler.getInstance().add(command)), point.name());
            assertTrue(failure.getCause() instanceof InjectedFailure, point.name());
            before.assertMatches(fixture.dataSet());
            assertTrue(UndoRedoHandler.getInstance().getUndoCommands().isEmpty());
            assertTrue(UndoRedoHandler.getInstance().getRedoCommands().isEmpty());
        }
    }

    @Test
    void staleRouteMembershipRejectsLockedRealInteriorJunctionApply() throws Exception {
        Fixture fixture = fixture();
        List<RelationMember> original = List.copyOf(fixture.route().getMembers());
        V022AtomicApplyTest.onEdt(() -> fixture.route().setMembers(
                List.of(original.get(1), original.get(0))));
        V022AtomicApplyTest.LiveState changed =
                V022AtomicApplyTest.LiveState.capture(fixture.dataSet());
        ApplyAlignmentEditPlanCommand command = new ApplyAlignmentEditPlanCommand(
                fixture.dataSet(), fixture.plan(), fixture.validator(),
                "Reject stale route membership");
        assertThrows(IllegalStateException.class, () -> V022AtomicApplyTest.onEdt(() ->
                UndoRedoHandler.getInstance().add(command)));
        changed.assertMatches(fixture.dataSet());
        assertTrue(UndoRedoHandler.getInstance().getUndoCommands().isEmpty());
        assertTrue(UndoRedoHandler.getInstance().getRedoCommands().isEmpty());
    }

    @Test
    void changedVisibleRasterRejectsHostRedoWithoutTouchingDatasetOrUnrelatedHistory() throws Exception {
        Fixture fixture = fixture();
        AtomicReference<LiveBPreviewService.VisibleRaster> current = new AtomicReference<>(raster());
        AtomicReference<String> reported = new AtomicReference<>();
        ApplyAlignmentEditPlanCommand alignment = new ApplyAlignmentEditPlanCommand(
                fixture.dataSet(), fixture.plan(),
                new VisibleSourceLockedApplyValidator(fixture.validator(), new LiveBPreviewService(),
                        fixture.captured(), current::get, () -> { }, reported::set), "Apply visible source");
        assertSourceStaleRedoHistory(fixture.dataSet(), alignment, () -> {
            LiveBPreviewService.VisibleRaster original = raster();
            int[] pixels = original.argb();
            pixels[360 * original.width() + 360] = 0xffffffff;
            current.set(new LiveBPreviewService.VisibleRaster(original.width(), original.height(), pixels,
                    original.minimumEast(), original.minimumNorth(), original.maximumEast(),
                    original.maximumNorth(), original.projectionUnitsPerViewPixel(),
                    original.groundMetersPerViewPixel(), original.nativePitchMeters(),
                    original.sourceIdentity(), original.projectionCode()));
        }, reported);
    }

    @Test
    void changedVisibleIdentityRejectsHostRedoWithoutTouchingDatasetOrUnrelatedHistory() throws Exception {
        Fixture fixture = fixture();
        AtomicReference<LiveBPreviewService.VisibleRaster> current = new AtomicReference<>(raster());
        AtomicReference<String> reported = new AtomicReference<>();
        ApplyAlignmentEditPlanCommand alignment = new ApplyAlignmentEditPlanCommand(
                fixture.dataSet(), fixture.plan(),
                new VisibleSourceLockedApplyValidator(fixture.validator(), new LiveBPreviewService(),
                        fixture.captured(), current::get, () -> { }, reported::set), "Apply visible source");
        assertSourceStaleRedoHistory(fixture.dataSet(), alignment, () -> {
            LiveBPreviewService.VisibleRaster original = raster();
            current.set(new LiveBPreviewService.VisibleRaster(original.width(), original.height(),
                    original.argb(), original.minimumEast(), original.minimumNorth(),
                    original.maximumEast(), original.maximumNorth(),
                    original.projectionUnitsPerViewPixel(), original.groundMetersPerViewPixel(),
                    original.nativePitchMeters(), "replacement-visible-layer", original.projectionCode()));
        }, reported);
    }

    @Test
    void changedManagedGenerationRejectsHostRedoWithoutTouchingDatasetOrUnrelatedHistory()
            throws Exception {
        ManagedFixture fixture = managedFixture();
        AtomicReference<ManagedHeatmapConfig> current =
                new AtomicReference<>(fixture.config().heatmap());
        AtomicReference<String> reported = new AtomicReference<>();
        ApplyAlignmentEditPlanCommand alignment = new ApplyAlignmentEditPlanCommand(
                fixture.dataSet(), fixture.plan(),
                new ManagedSourceLockedApplyValidator(fixture.validator(), new LiveBPreviewService(),
                        fixture.captured(), () -> requireManagedSourceCurrent(
                                fixture.config().heatmap(), current.get()), reported::set),
                "Apply managed source");
        assertSourceStaleRedoHistory(fixture.dataSet(), alignment,
                () -> current.set(managedConfig(38L, "hot").heatmap()), reported);
    }

    @Test
    void changedManagedSettingsRejectHostRedoWithoutTouchingDatasetOrUnrelatedHistory()
            throws Exception {
        ManagedFixture fixture = managedFixture();
        AtomicReference<ManagedHeatmapConfig> current =
                new AtomicReference<>(fixture.config().heatmap());
        AtomicReference<String> reported = new AtomicReference<>();
        ApplyAlignmentEditPlanCommand alignment = new ApplyAlignmentEditPlanCommand(
                fixture.dataSet(), fixture.plan(),
                new ManagedSourceLockedApplyValidator(fixture.validator(), new LiveBPreviewService(),
                        fixture.captured(), () -> requireManagedSourceCurrent(
                                fixture.config().heatmap(), current.get()), reported::set),
                "Apply managed source");
        assertSourceStaleRedoHistory(fixture.dataSet(), alignment,
                () -> current.set(managedConfig(37L, "blue").heatmap()), reported);
    }

    @Test
    void generationOnlyCompatibilityCommandRejectsStaleHostRedo() throws Exception {
        Fixture fixture = fixture();
        AtomicLong currentGeneration = new AtomicLong(fixture.plan().before().sourceGeneration());
        ApplyAlignmentEditPlanCommand alignment = new ApplyAlignmentEditPlanCommand(
                fixture.dataSet(), fixture.plan(), fixture.plan().before().datasetIdentity(),
                currentGeneration::get, "Apply captured generation");
        assertSourceStaleRedoHistory(fixture.dataSet(), alignment,
                currentGeneration::incrementAndGet);
    }

    private static void requireManagedSourceCurrent(ManagedHeatmapConfig captured,
            ManagedHeatmapConfig current) {
        if (!captured.hasSameManagedSource(current)) {
            throw new IllegalStateException("Managed source settings or generation changed");
        }
    }

    private static ManagedFixture managedFixture() throws Exception {
        DataSet dataSet = new DataSet();
        Node west = node(771, 0, -8);
        Node east = node(772, 0, 8);
        Way selected = way(773, west, east);
        dataSet.addPrimitive(west);
        dataSet.addPrimitive(east);
        dataSet.addPrimitive(selected);
        SelectionContext selection = new SelectionContext(selected, 0, 1,
                List.of(west, east), Set.of(west, east));
        AlignmentConfig config = managedConfig(37L, "hot");
        LiveBPreviewService service = new LiveBPreviewService();
        LiveBPreviewService.ManagedCaptureSeed[] seed =
                new LiveBPreviewService.ManagedCaptureSeed[1];
        SwingUtilities.invokeAndWait(() -> seed[0] = service.captureManagedSeed(
                dataSet, selection, config, "managed-selected-hot-g37"));
        BufferedImage image = new BufferedImage(600, 600, BufferedImage.TYPE_INT_ARGB);
        for (int y = 0; y < image.getHeight(); y++) {
            int gray = (int) Math.round(255.0 * (0.02 + 0.80 * Math.exp(
                    -0.5 * (y - 300.0) * (y - 300.0) / 1.44)));
            for (int x = 0; x < image.getWidth(); x++) {
                image.setRGB(x, y, 0xff000000 | gray << 16 | gray << 8 | gray);
            }
        }
        boolean[] valid = new boolean[image.getWidth() * image.getHeight()];
        java.util.Arrays.fill(valid, true);
        double equator = Math.scalb(256.0, 15) / 2.0;
        double halfWidth = image.getWidth() / 4.0;
        LiveBPreviewService.Captured captured = service.attachManagedRaster(seed[0],
                new ManagedModernPreviewSource.Raster(image, valid,
                        SupportedInputRasterTransform.webMercator(15,
                                equator - halfWidth, equator - halfWidth, 2.0),
                        "hot", 15, "managed-selected-hot-g37"));
        LiveBPreviewService.Computed computed = service.compute(captured, CancellationProbe.NONE);
        AlignmentEditPlan plan = new ModernSingleWayEditPlanAdapter().adapt(computed, 0);
        NetworkSnapshotCapture.CapturedSnapshot[] receipt =
                new NetworkSnapshotCapture.CapturedSnapshot[1];
        SwingUtilities.invokeAndWait(() -> receipt[0] = NetworkSnapshotCapture.captureBound(
                dataSet, captured.specification()));
        LiveNetworkSnapshotValidator validator = new LiveNetworkSnapshotValidator(
                receipt[0], plan, () -> plan.before().sourceGeneration());
        return new ManagedFixture(dataSet, config, captured, plan, validator);
    }

    private static AlignmentConfig managedConfig(long generation, String color) {
        ManagedHeatmapConfig heatmap = new ManagedHeatmapConfig("key", "policy", "signature",
                "session", "all", color, "", ".*", AlignmentMode.PRECISE_SHAPE,
                TrackerMode.CORRIDOR_AWARE, false, false, false, false, false, false,
                false, false, false, false, 7, 4, 3.0,
                InferenceMode.RAW_HIGH_RESOLUTION, 15, 15, 7.01, 1.56,
                IntensitySamplingMode.COLOR_MAPPING, generation);
        return new AlignmentConfig(heatmap, GeometryCleanupConfig.disabled());
    }

    private static void assertSourceStaleRedoHistory(DataSet dataSet,
            ApplyAlignmentEditPlanCommand alignment, Runnable changeSource) {
        assertSourceStaleRedoHistory(dataSet, alignment, changeSource, null);
    }

    private static void assertSourceStaleRedoHistory(DataSet dataSet,
            ApplyAlignmentEditPlanCommand alignment, Runnable changeSource,
            AtomicReference<String> reported) {
        Node unrelated = new Node(new LatLon(0.001, 0.001));
        AddCommand unrelatedHistory = new AddCommand(dataSet, unrelated);
        V022AtomicApplyTest.onEdt(() -> {
            UndoRedoHandler.getInstance().add(alignment);
            UndoRedoHandler.getInstance().add(unrelatedHistory);
            UndoRedoHandler.getInstance().undo();
            UndoRedoHandler.getInstance().undo();
        });
        assertEquals(List.of(alignment, unrelatedHistory),
                UndoRedoHandler.getInstance().getRedoCommands());
        changeSource.run();
        V022AtomicApplyTest.LiveState beforeRedo = V022AtomicApplyTest.LiveState.capture(dataSet);

        IllegalStateException failure = assertThrows(IllegalStateException.class,
                () -> V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().redo()));

        assertTrue(failure.getMessage() != null && !failure.getMessage().isBlank());
        if (reported != null) {
            assertTrue(reported.get() != null && reported.get().contains("recompute alignment"));
        }
        beforeRedo.assertMatches(dataSet);
        assertTrue(UndoRedoHandler.getInstance().getUndoCommands().isEmpty());
        assertEquals(List.of(unrelatedHistory), UndoRedoHandler.getInstance().getRedoCommands());
        assertTrue(unrelated.getDataSet() != dataSet);
    }

    @Test
    void realInteriorJunctionPlanRetainsOneHostEntryThroughTwentyCycles() throws Exception {
        Fixture fixture = fixture();
        assertTrue(!fixture.plan().createdPrimitives().isEmpty(),
                "The real route must exercise plan-local node creation");
        assertTrue(fixture.plan().writePrimitiveKeys().stream().anyMatch(key ->
                key.type() == PrimitiveKey.Type.NODE
                        && fixture.plan().before().primitives().containsKey(key)),
                "The real route must reuse and mutate an existing node identity");
        V022AtomicApplyTest.LiveState before =
                V022AtomicApplyTest.LiveState.capture(fixture.dataSet());
        List<RelationMember> relationMembers = List.copyOf(fixture.route().getMembers());
        ApplyAlignmentEditPlanCommand command = new ApplyAlignmentEditPlanCommand(
                fixture.dataSet(), fixture.plan(), fixture.validator(),
                "Apply real interior junction");
        V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().add(command));
        V022AtomicApplyTest.LiveState after =
                V022AtomicApplyTest.LiveState.capture(fixture.dataSet());
        assertEquals(before.nodes().size() + fixture.plan().createdPrimitives().size(),
                after.nodes().size());
        assertEquals(1, UndoRedoHandler.getInstance().getUndoCommands().size());
        assertEquals(relationMembers, fixture.route().getMembers());
        for (int cycle = 0; cycle < 20; cycle++) {
            V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().undo());
            before.assertMatches(fixture.dataSet());
            V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().redo());
            after.assertMatches(fixture.dataSet());
            assertEquals(1, UndoRedoHandler.getInstance().getUndoCommands().size());
            assertTrue(UndoRedoHandler.getInstance().getRedoCommands().isEmpty());
        }
        assertEquals(relationMembers, fixture.route().getMembers());
    }

    @Test
    void explicitCleanupDeletesOnlyCapturedOrdinaryUploadedShapeNode() throws Exception {
        CleanupFixture fixture = cleanupFixture(true);
        V022AtomicApplyTest.LiveState before = V022AtomicApplyTest.LiveState.capture(fixture.dataSet());
        V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().add(
                new ApplyAlignmentEditPlanCommand(fixture.dataSet(), fixture.plan(),
                        fixture.validator(), "Delete uploaded ordinary shape")));
        assertTrue(fixture.removable().isDeleted());
        assertTrue(!fixture.selected().getNodes().contains(fixture.removable()));
        V022AtomicApplyTest.LiveState after = V022AtomicApplyTest.LiveState.capture(fixture.dataSet());
        V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().undo());
        before.assertMatches(fixture.dataSet());
        V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().redo());
        after.assertMatches(fixture.dataSet());
        assertEquals(1, UndoRedoHandler.getInstance().getUndoCommands().size());
    }

    @Test
    void explicitCleanupPhysicallyRemovesNeverUploadedShapeNode() throws Exception {
        CleanupFixture fixture = cleanupFixture(false);
        assertTrue(fixture.removable().isNew());
        V022AtomicApplyTest.LiveState before = V022AtomicApplyTest.LiveState.capture(fixture.dataSet());
        V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().add(
                new ApplyAlignmentEditPlanCommand(fixture.dataSet(), fixture.plan(),
                        fixture.validator(), "Delete new ordinary shape")));
        assertTrue(fixture.removable().getDataSet() == null);
        assertTrue(!fixture.selected().getNodes().contains(fixture.removable()));
        V022AtomicApplyTest.LiveState after = V022AtomicApplyTest.LiveState.capture(fixture.dataSet());
        V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().undo());
        before.assertMatches(fixture.dataSet());
        V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().redo());
        after.assertMatches(fixture.dataSet());
        assertEquals(1, UndoRedoHandler.getInstance().getUndoCommands().size());
    }

    @Test
    void cleanupRemovalAuthorityExcludesProtectedAndUnsupportedOccurrences() throws Exception {
        for (String variant : List.of("tagged", "shared", "relation", "fixed", "bent",
                "disabled", "other-engine")) {
            DataSet dataSet = new DataSet();
            Node west = node(741, 0, 0);
            Node middle = node(742, variant.equals("bent") ? 1 : 0, 8);
            Node east = node(743, 0, 16);
            if (variant.equals("tagged")) {
                middle.put("name", "protected");
            }
            Way selected = way(744, west, middle, east);
            for (Node node : List.of(west, middle, east)) {
                dataSet.addPrimitive(node);
            }
            dataSet.addPrimitive(selected);
            if (variant.equals("shared")) {
                Node spur = node(745, 5, 8);
                dataSet.addPrimitive(spur);
                dataSet.addPrimitive(way(746, middle, spur));
            }
            if (variant.equals("relation")) {
                Relation relation = new Relation();
                relation.setMembers(List.of(new RelationMember("stop", middle)));
                relation.put("type", "route");
                relation.setOsmId(747, 1);
                dataSet.addPrimitive(relation);
            }
            SelectionContext selection = new SelectionContext(selected, 0, 2,
                    List.of(west, middle, east), variant.equals("fixed")
                            ? Set.of(middle) : Set.of());
            GeometryCleanupConfig cleanup = variant.equals("disabled")
                    ? GeometryCleanupConfig.disabled()
                    : GeometryCleanupConfig.disabled()
                            .withMode(GeometryCleanupMode.REDUCE_POINTS_ONLY);
            TrackerMode engine = variant.equals("other-engine")
                    ? TrackerMode.PROBABILISTIC : TrackerMode.CORRIDOR_AWARE;
            AlignmentConfig config = new AlignmentConfig(
                    config().heatmap().withTrackerMode(engine), cleanup);
            RecoveryPermissions permissions = new RecoveryPermissions(false, 7.0, 7.0,
                    JunctionPolicy.REATTACH, true);
            LiveBPreviewService.Captured[] captured = new LiveBPreviewService.Captured[1];
            SwingUtilities.invokeAndWait(() -> captured[0] = new LiveBPreviewService().capture(
                    dataSet, selection, straightRaster(), config, false, permissions));
            PrimitiveKey middleKey = PrimitiveKey.existing(PrimitiveKey.Type.NODE,
                    middle.getUniqueId());
            assertTrue(captured[0].network().closure().removableExistingNodeKeys().isEmpty(),
                    variant);
            if (List.of("tagged", "shared", "relation", "fixed").contains(variant)) {
                assertTrue(captured[0].network().closure().protectedExistingNodeKeys()
                        .contains(middleKey), variant);
            } else {
                assertTrue(captured[0].network().closure().movableExistingNodeKeys()
                        .contains(middleKey), variant);
            }
        }
    }

    @Test
    void sameReceiverAtTwoSelectedJunctionsUsesTwoCompleteMeasuredRanges() throws Exception {
        DataSet dataSet = new DataSet();
        Node left = node(751, 0, -40);
        Node right = node(752, 0, 40);
        Way selected = way(753, left, right);
        Node farLeftSouth = node(754, -50, -42);
        Node leftSouthPort = node(755, -35, -42);
        Node leftSouth = node(756, -10, -42);
        Node leftNorth = node(757, 10, -42);
        Node leftNorthPort = node(758, 35, -42);
        Node topLeft = node(759, 50, -42);
        Node topRight = node(760, 50, 42);
        Node rightNorthPort = node(761, 35, 42);
        Node rightNorth = node(762, 10, 42);
        Node rightSouth = node(763, -10, 42);
        Node rightSouthPort = node(764, -35, 42);
        Node farRightSouth = node(765, -50, 42);
        Way receiver = way(766, farLeftSouth, leftSouthPort, leftSouth, left,
                leftNorth, leftNorthPort, topLeft, topRight, rightNorthPort,
                rightNorth, right, rightSouth, rightSouthPort, farRightSouth);
        for (Node node : List.of(left, right, farLeftSouth, leftSouthPort, leftSouth,
                leftNorth, leftNorthPort, topLeft, topRight, rightNorthPort,
                rightNorth, rightSouth, rightSouthPort, farRightSouth)) {
            dataSet.addPrimitive(node);
        }
        dataSet.addPrimitive(selected);
        dataSet.addPrimitive(receiver);
        Relation route = new Relation();
        route.setMembers(List.of(new RelationMember("bridge", selected),
                new RelationMember("loop", receiver)));
        route.put("type", "route");
        route.setOsmId(767, 1);
        route.setModified(false);
        dataSet.addPrimitive(route);
        SelectionContext selection = new SelectionContext(selected, 0, 1,
                List.of(left, right), Set.of());
        RecoveryPermissions permissions = new RecoveryPermissions(false, 7.0, 7.0,
                JunctionPolicy.REATTACH, true);
        LiveBPreviewService.Captured[] captured = new LiveBPreviewService.Captured[1];
        SwingUtilities.invokeAndWait(() -> captured[0] = new LiveBPreviewService().capture(
                dataSet, selection, sameReceiverRaster(), config(), false, permissions));
        PrimitiveKey receiverKey = PrimitiveKey.existing(PrimitiveKey.Type.WAY, 766);
        assertEquals(2, captured[0].network().closure().editableWayOccurrences()
                .get(receiverKey).size());
        assertEquals(4, captured[0].network().closure().externalPorts().stream()
                .filter(port -> port.wayKey().equals(receiverKey)).count());
        LiveBPreviewService.Computed computed = new LiveBPreviewService().compute(
                captured[0], CancellationProbe.NONE);
        AlignmentEditPlan plan = new ModernSingleWayEditPlanAdapter().adapt(computed, 0);
        assertEquals(Set.of(PrimitiveKey.existing(PrimitiveKey.Type.WAY, 753), receiverKey),
                plan.finalPreviewWays().keySet());
        assertTrue(plan.validation().findingCodes().stream()
                .noneMatch(code -> code.startsWith("final-topology:")));
        PrimitiveKey routeKey = PrimitiveKey.existing(PrimitiveKey.Type.RELATION, 767);
        assertEquals(plan.before().primitives().get(routeKey), plan.after().primitives().get(routeKey));
        for (var port : captured[0].network().closure().externalPorts()) {
            if (port.wayKey().equals(receiverKey)) {
                assertEquals(plan.before().primitives().get(port.boundaryNodeKey()),
                        plan.after().primitives().get(port.boundaryNodeKey()));
            }
        }
        for (Node connector : List.of(topLeft, topRight)) {
            PrimitiveKey key = PrimitiveKey.existing(PrimitiveKey.Type.NODE,
                    connector.getUniqueId());
            assertEquals(plan.before().primitives().get(key), plan.after().primitives().get(key));
        }
        LiveBPreviewService.Captured[] missingCaptured = new LiveBPreviewService.Captured[1];
        SwingUtilities.invokeAndWait(() -> missingCaptured[0] = new LiveBPreviewService().capture(
                dataSet, selection, sameReceiverRaster(false), config(), false, permissions));
        LiveBPreviewService.Computed missingComputed = new LiveBPreviewService().compute(
                missingCaptured[0], CancellationProbe.NONE);
        IllegalArgumentException missing = assertThrows(IllegalArgumentException.class,
                () -> new ModernSingleWayEditPlanAdapter().adapt(missingComputed, 0));
        assertTrue(missing.getMessage().contains("incident approach evidence"),
                missing::getMessage);
        NetworkSnapshotCapture.CapturedSnapshot[] receipt =
                new NetworkSnapshotCapture.CapturedSnapshot[1];
        SwingUtilities.invokeAndWait(() -> receipt[0] = NetworkSnapshotCapture.captureBound(
                dataSet, captured[0].specification()));
        LiveNetworkSnapshotValidator validator = new LiveNetworkSnapshotValidator(
                receipt[0], plan, () -> plan.before().sourceGeneration());
        V022AtomicApplyTest.LiveState before = V022AtomicApplyTest.LiveState.capture(dataSet);
        V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().add(
                new ApplyAlignmentEditPlanCommand(dataSet, plan, validator, "Apply coupled loop")));
        for (var entry : plan.finalPreviewWays().entrySet()) {
            Way live = entry.getKey().equals(receiverKey) ? receiver : selected;
            assertEquals(entry.getValue().size(), live.getNodesCount());
            for (int index = 0; index < live.getNodesCount(); index++) {
                assertEquals(entry.getValue().get(index).latitudeDegrees(),
                        live.getNode(index).lat(), 1.0e-9);
                assertEquals(entry.getValue().get(index).longitudeDegrees(),
                        live.getNode(index).lon(), 1.0e-9);
            }
        }
        V022AtomicApplyTest.LiveState after = V022AtomicApplyTest.LiveState.capture(dataSet);
        for (int cycle = 0; cycle < 20; cycle++) {
            V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().undo());
            before.assertMatches(dataSet);
            V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().redo());
            after.assertMatches(dataSet);
            assertEquals(1, UndoRedoHandler.getInstance().getUndoCommands().size());
        }
        V022AtomicApplyTest.onEdt(() -> UndoRedoHandler.getInstance().undo());
        before.assertMatches(dataSet);
        UndoRedoHandler.getInstance().clean();
        for (ApplyAlignmentEditPlanCommand.MutationPoint point
                : ApplyAlignmentEditPlanCommand.MutationPoint.values()) {
            ApplyAlignmentEditPlanCommand failureCommand = new ApplyAlignmentEditPlanCommand(
                    dataSet, plan, validator, "Inject coupled loop failure", reached -> {
                        if (reached == point) {
                            throw new InjectedFailure(point);
                        }
                    });
            assertThrows(IllegalStateException.class, () -> V022AtomicApplyTest.onEdt(() ->
                    UndoRedoHandler.getInstance().add(failureCommand)), point.name());
            before.assertMatches(dataSet);
            assertTrue(UndoRedoHandler.getInstance().getUndoCommands().isEmpty());
            assertTrue(UndoRedoHandler.getInstance().getRedoCommands().isEmpty());
        }
        Node spur = node(768, -12, -55);
        Way extraIncident = way(769, left, spur);
        dataSet.addPrimitive(spur);
        dataSet.addPrimitive(extraIncident);
        V022AtomicApplyTest.LiveState changed = V022AtomicApplyTest.LiveState.capture(dataSet);
        ApplyAlignmentEditPlanCommand stale = new ApplyAlignmentEditPlanCommand(
                dataSet, plan, validator, "Reject new incident after review");
        assertThrows(IllegalStateException.class, () -> V022AtomicApplyTest.onEdt(() ->
                UndoRedoHandler.getInstance().add(stale)));
        changed.assertMatches(dataSet);
        LiveBPreviewService.Captured[] extraCaptured = new LiveBPreviewService.Captured[1];
        SwingUtilities.invokeAndWait(() -> extraCaptured[0] = new LiveBPreviewService().capture(
                dataSet, selection, sameReceiverRaster(), config(), false, permissions));
        LiveBPreviewService.Computed extraComputed = new LiveBPreviewService().compute(
                extraCaptured[0], CancellationProbe.NONE);
        IllegalArgumentException extra = assertThrows(IllegalArgumentException.class,
                () -> new ModernSingleWayEditPlanAdapter().adapt(extraComputed, 0));
        assertTrue(extra.getMessage().contains("bounded terminal-through topology"),
                extra::getMessage);
    }

    private static CleanupFixture cleanupFixture(boolean uploaded) throws Exception {
        DataSet dataSet = new DataSet();
        Node west = node(721, 0, 0);
        Node removable = uploaded ? node(722, 0, 8) : new Node(new LatLon(0, longitude(8)));
        Node east = node(723, 0, 16);
        Way selected = way(724, west, removable, east);
        for (Node node : List.of(west, removable, east)) {
            dataSet.addPrimitive(node);
        }
        dataSet.addPrimitive(selected);
        SelectionContext selection = new SelectionContext(selected, 0, 2,
                List.of(west, removable, east), Set.of());
        GeometryCleanupConfig cleanup = GeometryCleanupConfig.disabled()
                .withMode(GeometryCleanupMode.REDUCE_POINTS_ONLY);
        AlignmentConfig config = new AlignmentConfig(
                config().heatmap().withTrackerMode(TrackerMode.CORRIDOR_AWARE), cleanup);
        LiveBPreviewService.Captured[] captured = new LiveBPreviewService.Captured[1];
        RecoveryPermissions permissions = new RecoveryPermissions(false, 7.0, 7.0,
                JunctionPolicy.REATTACH, true);
        SwingUtilities.invokeAndWait(() -> captured[0] = new LiveBPreviewService().capture(
                dataSet, selection, straightRaster(), config, false, permissions));
        PrimitiveKey removedKey = PrimitiveKey.existing(PrimitiveKey.Type.NODE,
                removable.getUniqueId());
        LiveBPreviewService.Computed computed = new LiveBPreviewService().compute(
                captured[0], CancellationProbe.NONE);
        assertTrue(!computed.pipeline().routes().get(0).pointIds().contains(
                new ExistingWayNodeOccurrence(PrimitiveKey.existing(PrimitiveKey.Type.WAY,
                        selected.getUniqueId()), removedKey, 1)));
        AlignmentEditPlan plan = new ModernSingleWayEditPlanAdapter().adapt(computed, 0);
        assertEquals(Set.of(removedKey), plan.removedPrimitives().keySet());
        assertEquals(Set.of(removedKey), captured[0].network().closure()
                .removableExistingNodeKeys());
        NetworkSnapshotCapture.CapturedSnapshot[] receipt =
                new NetworkSnapshotCapture.CapturedSnapshot[1];
        SwingUtilities.invokeAndWait(() -> receipt[0] = NetworkSnapshotCapture.captureBound(
                dataSet, captured[0].specification()));
        LiveNetworkSnapshotValidator validator = new LiveNetworkSnapshotValidator(
                receipt[0], plan, () -> plan.before().sourceGeneration());
        return new CleanupFixture(dataSet, selected, removable, plan, validator);
    }

    private static Fixture fixture() throws Exception {
        DataSet dataSet = new DataSet();
        Node west = node(701, 0, -8);
        Node junction = node(702, 0, 8);
        Node continuation = node(703, 0, 18);
        Node farSouth = node(704, -49, 10);
        Node southPort = node(705, -31, 10);
        Node south = node(706, -8, 10);
        Node middle = node(707, 8, 10);
        Node north = node(708, 18, 10);
        Node northPort = node(709, 31, 10);
        Node farNorth = node(710, 49, 10);
        Way selected = way(711, west, junction, continuation);
        Way receiver = way(712, farSouth, southPort, south, junction,
                middle, north, northPort, farNorth);
        for (Node node : List.of(west, junction, continuation, farSouth, southPort,
                south, middle, north, northPort, farNorth)) {
            dataSet.addPrimitive(node);
        }
        dataSet.addPrimitive(selected);
        dataSet.addPrimitive(receiver);
        Relation route = new Relation();
        route.setMembers(List.of(new RelationMember("selected", selected),
                new RelationMember("receiver", receiver)));
        route.put("type", "route");
        route.put("route", "bicycle");
        route.setOsmId(713, 1);
        route.setModified(false);
        dataSet.addPrimitive(route);
        SelectionContext selection = new SelectionContext(selected, 0, 1,
                List.of(west, junction), Set.of());
        RecoveryPermissions permissions = new RecoveryPermissions(false, 7.0, 7.0,
                JunctionPolicy.REATTACH, true);
        LiveBPreviewService.Captured[] captured = new LiveBPreviewService.Captured[1];
        SwingUtilities.invokeAndWait(() -> captured[0] = new LiveBPreviewService().capture(
                dataSet, selection, raster(), config(), false, permissions));
        LiveBPreviewService.Computed computed = new LiveBPreviewService().compute(
                captured[0], CancellationProbe.NONE);
        AlignmentEditPlan plan = new ModernSingleWayEditPlanAdapter().adapt(computed, 0);
        NetworkSnapshotCapture.CapturedSnapshot[] receipt =
                new NetworkSnapshotCapture.CapturedSnapshot[1];
        SwingUtilities.invokeAndWait(() -> receipt[0] = NetworkSnapshotCapture.captureBound(
                dataSet, captured[0].specification()));
        LiveNetworkSnapshotValidator validator = new LiveNetworkSnapshotValidator(
                receipt[0], plan, () -> plan.before().sourceGeneration());
        return new Fixture(dataSet, plan, validator, route, captured[0]);
    }

    private static LiveBPreviewService.VisibleRaster raster() {
        int size = 720;
        int[] argb = new int[size * size];
        for (int y = 0; y < size; y++) {
            for (int x = 0; x < size; x++) {
                double selectedDistance = (y - 348.0) / 6.0;
                double receiverDistance = (x - 408.0) / 6.0;
                double selected = Math.exp(-0.5 * selectedDistance * selectedDistance / 1.44);
                double receiver = Math.exp(-0.5 * receiverDistance * receiverDistance / 1.44);
                int gray = (int) Math.round(255.0 * (0.02 + 0.80
                        * Math.max(selected, receiver)));
                argb[y * size + x] = 0xff000000 | gray << 16 | gray << 8 | gray;
            }
        }
        return new LiveBPreviewService.VisibleRaster(size, size, argb,
                -60.0, -60.0, 60.0, 60.0, 1.0, 1.0, OptionalDouble.of(1.0),
                "production-interior-transaction", "EPSG:3857");
    }

    private static LiveBPreviewService.VisibleRaster straightRaster() {
        int size = 720;
        int[] argb = new int[size * size];
        for (int y = 0; y < size; y++) {
            double distance = (y - size / 2.0) / 6.0;
            int gray = (int) Math.round(255.0 * (0.02 + 0.80
                    * Math.exp(-0.5 * distance * distance / 1.44)));
            java.util.Arrays.fill(argb, y * size, (y + 1) * size,
                    0xff000000 | gray << 16 | gray << 8 | gray);
        }
        return new LiveBPreviewService.VisibleRaster(size, size, argb,
                -60.0, -60.0, 60.0, 60.0, 1.0, 1.0, OptionalDouble.of(1.0),
                "production-cleanup-deletion", "EPSG:3857");
    }

    private static LiveBPreviewService.VisibleRaster sameReceiverRaster() {
        return sameReceiverRaster(true);
    }

    private static LiveBPreviewService.VisibleRaster sameReceiverRaster(boolean rightCorridor) {
        int size = 1440;
        int[] argb = new int[size * size];
        for (int y = 0; y < size; y++) {
            for (int x = 0; x < size; x++) {
                double selectedDistance = (y - 720.0) / 6.0;
                double leftDistance = (x - 456.0) / 6.0;
                double rightDistance = (x - 984.0) / 6.0;
                double selected = Math.exp(-0.5 * selectedDistance * selectedDistance / 1.44);
                double left = Math.exp(-0.5 * leftDistance * leftDistance / 1.44);
                double right = rightCorridor
                        ? Math.exp(-0.5 * rightDistance * rightDistance / 1.44) : 0.0;
                int gray = (int) Math.round(255.0 * (0.02 + 0.80
                        * Math.max(selected, Math.max(left, right))));
                argb[y * size + x] = 0xff000000 | gray << 16 | gray << 8 | gray;
            }
        }
        return new LiveBPreviewService.VisibleRaster(size, size, argb,
                -120.0, -120.0, 120.0, 120.0, 1.0, 1.0, OptionalDouble.of(1.0),
                "production-coupled-same-receiver", "EPSG:3857");
    }

    private static AlignmentConfig config() {
        ManagedHeatmapConfig heatmap = new ManagedHeatmapConfig("", "policy", "signature",
                "session", "all", "hot", "", ".*", AlignmentMode.PRECISE_SHAPE,
                TrackerMode.PROBABILISTIC, false, false, false, false, false, false,
                false, false, false, false, 7, 4, 3.0,
                InferenceMode.RAW_HIGH_RESOLUTION, 15, 15, 7.01, 1.56,
                IntensitySamplingMode.COLOR_MAPPING, 0L);
        return new AlignmentConfig(heatmap, GeometryCleanupConfig.disabled());
    }

    private static Node node(long id, double northMeters, double eastMeters) {
        Node node = new Node(new LatLon(Math.toDegrees(northMeters / 6_378_137.0),
                longitude(eastMeters)));
        node.setOsmId(id, 1);
        node.setModified(false);
        return node;
    }

    private static double longitude(double eastMeters) {
        return Math.toDegrees(eastMeters / 6_378_137.0);
    }

    private static Way way(long id, Node... nodes) {
        Way way = new Way();
        way.setNodes(List.of(nodes));
        way.setOsmId(id, 1);
        way.setModified(false);
        return way;
    }

    private record Fixture(DataSet dataSet, AlignmentEditPlan plan,
            LiveNetworkSnapshotValidator validator, Relation route,
            LiveBPreviewService.Captured captured) { }

    private record ManagedFixture(DataSet dataSet, AlignmentConfig config,
            LiveBPreviewService.Captured captured, AlignmentEditPlan plan,
            LiveNetworkSnapshotValidator validator) { }

    private record CleanupFixture(DataSet dataSet, Way selected, Node removable,
            AlignmentEditPlan plan, LiveNetworkSnapshotValidator validator) { }

    private static final class InjectedFailure extends RuntimeException {
        private static final long serialVersionUID = 1L;

        InjectedFailure(ApplyAlignmentEditPlanCommand.MutationPoint point) {
            super("injected at " + point);
        }
    }
}
