name: Build

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Build
        run: sh gradlew clean build
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: wayheatmaptracer
          path: build/libs/*.jar
